"""
Comparison test: verify that the INCAR, STRU and orb files generated by
aiida_orbgen.interfaces match the real files under project/pbe.

How to run:
    cd /home/liguozhou/abacus/calculations/orbgen/aiida_orbgen
    python tests/test_project_pbe.py
    # or
    pytest tests/test_project_pbe.py -v
"""

import os
import sys
import json
import tempfile
import shutil
from pathlib import Path

import pytest

# Path setup
ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR / "src"))

# Add SIAB to the path
#
# ``append`` rather than ``insert(0, ...)``: this machine has two copies of SIAB,
# and this one is missing the ``simpson`` patch (scipy >= 1.12 removed
# ``scipy.integrate.simps``). Putting it first would shadow the usable copy in
# the workspace and pollute every later test in the same process.
SIAB_PATH = Path("/home/liguozhou/install/ABACUS-CSW-NAO")
if SIAB_PATH.exists() and str(SIAB_PATH) not in sys.path:
    sys.path.append(str(SIAB_PATH))

# Check whether SIAB is available
try:
    import SIAB  # noqa: F401
    SIAB_AVAILABLE = True
except ImportError:
    SIAB_AVAILABLE = False

siab_required = pytest.mark.skipif(
    not SIAB_AVAILABLE,
    reason="SIAB library not available"
)

# Reference data directory.
#
# It used to be hard-coded to ``project/pbe``; that data was later moved and
# renamed, so the whole module failed with "AssertionError: STRU not found" --
# which looked like broken code while the real cause was a missing fixture. Now
# the first usable candidate location is used; if none is found the whole module
# is skipped, and ``requires_fixture`` explains why.
_LOCAL = Path("/home/liguozhou/abacus/calculations/orbgen/project")
PROJECT_CANDIDATES = (
    _LOCAL / "pbe",                                  # original location
    _LOCAL / "orbgen_api" / "static",                # actual current location
    _LOCAL / "test" / "pbe",
    _LOCAL / "_archive_old_install_20260929" / "orbgen",
)


def _is_reference_tree(path: Path) -> bool:
    return (
        path is not None
        and (path / "pbe_orbgen.json").is_file()
        and (path / "primitive_jy").is_dir()
        and (path / "U-dimer-1.89-9au" / "INPUT").is_file()
    )


PROJECT_DIR = next((p for p in PROJECT_CANDIDATES if _is_reference_tree(p)), None)

if PROJECT_DIR is None:  # keep the module importable; every test is skipped
    PROJECT_DIR = PROJECT_CANDIDATES[0]
    pytestmark = pytest.mark.skipif(
        True,
        reason="reference project data not found in "
               + ", ".join(str(p) for p in PROJECT_CANDIDATES),
    )
else:
    pytestmark = pytest.mark.skipif(
        not SIAB_AVAILABLE, reason="SIAB library not available"
    )

JSON_CONFIG_PATH = PROJECT_DIR / "pbe_orbgen.json"
PRIMITIVE_JY_DIR = PROJECT_DIR / "primitive_jy"
JOB_DIR = PROJECT_DIR / "U-dimer-1.89-9au"
EXPECTED_ORB = PRIMITIVE_JY_DIR / "U_gga_9au_100Ry_27s27p26d26f25g.orb"
EXPECTED_INPUT = JOB_DIR / "INPUT"
EXPECTED_STRU = JOB_DIR / "STRU"

from aiida_orbgen.interfaces.nsw import generate_nsw, compute_nbes_per_l
from aiida_orbgen.interfaces.incar import generate_incar, parse_incar
from aiida_orbgen.interfaces.stru import generate_stru, dft_folder_name


# ============================================================================
# 1. NSW orbital comparison
# ============================================================================

@siab_required
class TestNswComparison:
    """Compare the generated NSW orbitals with the real NSW orbitals."""

    def test_nsw_file_exists(self):
        """Verify that project/pbe/primitive_jy/U_gga_9au_100Ry_27s27p26d26f25g.orb exists."""
        assert EXPECTED_ORB.exists(), f"NSW file not found: {EXPECTED_ORB}"
        assert EXPECTED_ORB.stat().st_size > 0, "NSW file is empty"

    def test_nsw_filename_format(self):
        """Verify that the NSW file name follows U_gga_9au_100Ry_27s27p26d26f25g.orb."""
        filename = EXPECTED_ORB.name
        assert filename == "U_gga_9au_100Ry_27s27p26d26f25g.orb"
        assert filename.startswith("U_gga_9au_100Ry_")
        assert filename.endswith(".orb")

    def test_nsw_nbes_computation(self):
        """Verify that the computed nbes matches the file name.

        File name: 27s27p26d26f25g
        Meaning: l=0:27, l=1:27, l=2:26, l=3:26, l=4:25
        """
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)
        nbes = compute_nbes_per_l(
            rcut=float(config["bessel_nao_rcut"][0]),
            ecut=float(config["ecutjy"]),
            lmaxmax=config["geoms"][0]["lmaxmax"],
            primitive_type=config["primitive_type"],
        )
        nbes_int = [int(n) for n in nbes]
        # File name: 27s27p26d26f25g means [27, 27, 26, 26, 25]
        # nbes returns the reduced values (already minus 1), and so is the file name
        assert nbes_int == [27, 27, 26, 26, 25], (
            f"Expected [27, 27, 26, 26, 25], got {nbes_int}"
        )

    def test_nsw_generation_matches(self, tmp_path):
        """Regenerate the NSW through the interface and verify the content matches."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        # Generate through the interface
        generated_path = generate_nsw(
            config,
            output_dir=str(tmp_path),
            lmaxmax=config["geoms"][0]["lmaxmax"],
        )

        # Verify that the file name matches
        assert Path(generated_path).name == EXPECTED_ORB.name

        # Verify that the content size is roughly the same
        gen_size = os.path.getsize(generated_path)
        exp_size = EXPECTED_ORB.stat().st_size
        # The NSW orbital format is the same, so the sizes should be close
        assert abs(gen_size - exp_size) / exp_size < 0.1, (
            f"NSW file size differs: generated={gen_size}, expected={exp_size}"
        )

        # Verify that the file header matches
        with open(generated_path) as f:
            gen_content = f.read()
        with open(EXPECTED_ORB) as f:
            exp_content = f.read()

        # Extract the header (first 1500 characters, covering dr and other parameters)
        gen_header = gen_content[:1500]
        exp_header = exp_content[:1500]
        # The header must contain the element symbol, ecut, rcut and dr
        # Actual format: "Element                     U" (multiple spaces)
        for keyword in ["Element", "U", "Energy Cutoff", "Radius Cutoff",
                        "Lmax", "Sorbital", "Porbital", "Dorbital",
                        "Forbital", "Gorbital", "Mesh", "dr"]:
            assert keyword in gen_header, f"Missing '{keyword}' in generated NSW"

        # Numeric parameters (original JSON types kept: "100" (int), "9" (int), "0.01" (float))
        assert "100" in gen_header  # ecut
        assert " 9\n" in gen_header or "9 " in gen_header  # rcut
        assert "0.01" in gen_header  # dr


# ============================================================================
# 2. INPUT (INCAR) comparison
# ============================================================================

@siab_required
class TestIncarComparison:
    """Compare the generated INPUT with the real INPUT."""

    def test_input_file_exists(self):
        """Verify that project/pbe/U-dimer-1.89-9au/INPUT exists."""
        assert EXPECTED_INPUT.exists(), f"INPUT not found: {EXPECTED_INPUT}"
        assert EXPECTED_INPUT.stat().st_size > 0

    def test_input_key_parameters(self):
        """Verify that the key INPUT parameters match the real ones."""
        params = parse_incar(str(EXPECTED_INPUT))

        # Key parameters
        assert str(params.get("basis_type")) == "lcao"
        assert str(params.get("ecutwfc")) == "150"
        assert str(params.get("nspin")) == "1"
        assert str(params.get("nbands")) == "40"
        assert str(params.get("bessel_nao_rcut")) == "9"
        assert str(params.get("ks_solver")) == "genelpa"
        assert str(params.get("smearing_method")) == "gauss"
        assert "0.02" in str(params.get("smearing_sigma"))
        assert str(params.get("mixing_type")) == "broyden"
        assert "0.4" in str(params.get("mixing_beta"))
        assert str(params.get("mixing_ndim")) == "12"
        assert str(params.get("gamma_only")) == "1"
        assert str(params.get("out_wfc_lcao")) == "1"
        assert str(params.get("out_mat_hs")) == "1 12"
        assert str(params.get("out_mat_tk")) == "1 12"

    def test_input_generation_matches(self, tmp_path):
        """Regenerate the INPUT through the interface and verify the key parameters match."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        # Generate through the interface
        gen_path = generate_incar(
            config,
            output_path=str(tmp_path / "INPUT"),
        )

        # Parse the generated file
        gen_params = parse_incar(gen_path)
        exp_params = parse_incar(str(EXPECTED_INPUT))

        # Path-like parameters are converted to absolute paths by SIAB, while the
        # interface layer can only use relative paths, so those fields are skipped
        SKIP_KEYS = {"pseudo_dir", "orbital_dir"}

        # Compare every parameter present in both
        for key in gen_params:
            if key in exp_params and key not in SKIP_KEYS:
                assert str(gen_params[key]) == str(exp_params[key]), (
                    f"Parameter '{key}' mismatch: "
                    f"generated={gen_params[key]}, expected={exp_params[key]}"
                )

    def test_input_no_extra_user_params_in_expected(self):
        """Verify the real INPUT has no extra DFT parameters beyond the user's and autoset ones."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        # Parse the real INPUT
        exp_params = parse_incar(str(EXPECTED_INPUT))

        # DFT parameters explicitly provided by the user
        user_dft_params = {
            "ecutwfc", "smearing_method", "smearing_sigma",
            "mixing_type", "mixing_beta", "mixing_ndim"
        }

        for key in user_dft_params:
            assert key in exp_params, f"User-specified param '{key}' missing in INPUT"

    def test_input_lcao_derived_from_fit_basis(self):
        """basis_type should be inferred as lcao from fit_basis='jy'."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)
        assert config.get("fit_basis") == "jy"
        # This rule: fit_basis='jy' => basis_type='lcao'
        # is already implemented in the interface's _extract_dftparam
        params = parse_incar(str(EXPECTED_INPUT))
        assert params.get("basis_type") == "lcao"


# ============================================================================
# 3. STRU comparison
# ============================================================================

@siab_required
class TestStruComparison:
    """Compare the generated STRU with the real STRU."""

    def test_stru_file_exists(self):
        """Verify that project/pbe/U-dimer-1.89-9au/STRU exists."""
        assert EXPECTED_STRU.exists(), f"STRU not found: {EXPECTED_STRU}"

    def test_stru_key_sections(self):
        """Verify the key STRU sections."""
        content = EXPECTED_STRU.read_text()
        assert "ATOMIC_SPECIES" in content
        assert "U 1.000000 U.pbe-n-nc.upf" in content
        assert "NUMERICAL_ORBITAL" in content
        assert "U_gga_9au_100Ry_27s27p26d26f25g.orb" in content
        assert "LATTICE_CONSTANT" in content
        assert "30.000000" in content
        assert "LATTICE_VECTORS" in content
        assert "ATOMIC_POSITIONS" in content
        assert "Cartesian_angstrom_center_xyz" in content
        assert "0.00" in content  # starting magnetization
        assert "2       //number of atoms" in content

    def test_stru_atom_coordinates(self):
        """Verify the STRU atom coordinates.

        shift = 30.0 / 2 / 1.8897259886 = 7.93765873
        z coordinate of the second dimer atom = 1.89 + shift = 9.82765873
        """
        content = EXPECTED_STRU.read_text()
        # bond_length 1.89
        shift = 30.0 / 2 / 1.8897259886
        expected_z = 1.89 + shift
        assert f"{expected_z:.8f}" in content

    def test_stru_generation_matches(self, tmp_path):
        """Regenerate the STRU through the interface and verify it matches the real one."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        gen_path = generate_stru(
            config,
            output_path=str(tmp_path / "STRU"),
            bond_length=1.89,
            orb_filename="U_gga_9au_100Ry_27s27p26d26f25g.orb",
        )

        gen_content = Path(gen_path).read_text()
        exp_content = EXPECTED_STRU.read_text()

        # Compare the key fields
        for keyword in [
            "ATOMIC_SPECIES",
            "U 1.000000 U.pbe-n-nc.upf",
            "NUMERICAL_ORBITAL",
            "U_gga_9au_100Ry_27s27p26d26f25g.orb",
            "LATTICE_CONSTANT",
            "30.000000",
            "Cartesian_angstrom_center_xyz",
            "0.00",
            "2       //number of atoms",
            "7.93765873 7.93765873 7.93765873 0 0 0",
            "7.93765873 7.93765873 9.82765873 0 0 0",
        ]:
            assert keyword in gen_content, f"Missing '{keyword}' in generated STRU"
            assert keyword in exp_content, f"Missing '{keyword}' in expected STRU"

    def test_dft_folder_name(self):
        """Verify that dft_folder_name matches the real folder name."""
        # Real folder: U-dimer-1.89-9au
        assert JOB_DIR.name == dft_folder_name("U", "dimer", 1.89, rcut=9)


# ============================================================================
# 4. Integration comparison - all three files together
# ============================================================================

@siab_required
class TestFullComparison:
    """Full comparison test: verify the generation results of all three files at once."""

    def test_generate_all_three_files(self, tmp_path):
        """Generate the three files NSW + INPUT + STRU in one go."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        # 1. Generate the NSW
        nsw_path = generate_nsw(
            config,
            output_dir=str(tmp_path / "primitive_jy"),
            lmaxmax=config["geoms"][0]["lmaxmax"],
        )

        # 2. Generate the INPUT
        job_folder = tmp_path / "U-dimer-1.89-9au"
        job_folder.mkdir()
        input_path = generate_incar(
            config,
            output_path=str(job_folder / "INPUT"),
        )

        # 3. Generate the STRU
        stru_path = generate_stru(
            config,
            output_path=str(job_folder / "STRU"),
            bond_length=1.89,
            orb_filename=Path(nsw_path).name,
        )

        # Verify that the files exist
        assert os.path.exists(nsw_path)
        assert os.path.exists(input_path)
        assert os.path.exists(stru_path)

        # Verify that the NSW file name matches project/pbe
        assert Path(nsw_path).name == "U_gga_9au_100Ry_27s27p26d26f25g.orb"
        assert Path(nsw_path).name == EXPECTED_ORB.name

        # Verify that the STRU references the correct NSW
        stru_content = Path(stru_path).read_text()
        assert Path(nsw_path).name in stru_content

    def test_nsw_content_size_consistent(self):
        """Verify that the generated NSW file size roughly matches the real file."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        with tempfile.TemporaryDirectory() as tmp:
            gen_path = generate_nsw(
                config,
                output_dir=tmp,
                lmaxmax=config["geoms"][0]["lmaxmax"],
            )
            gen_size = os.path.getsize(gen_path)
            exp_size = EXPECTED_ORB.stat().st_size

            # The file size difference should be < 5%
            ratio = abs(gen_size - exp_size) / exp_size
            assert ratio < 0.05, (
                f"NSW file size differs by {ratio*100:.1f}%: "
                f"generated={gen_size}, expected={exp_size}"
            )

    def test_input_parameter_set_consistent(self):
        """Verify that the INPUT parameter set matches the real file (same values allowed)."""
        with open(JSON_CONFIG_PATH) as f:
            config = json.load(f)

        with tempfile.TemporaryDirectory() as tmp:
            gen_path = generate_incar(
                config,
                output_path=str(Path(tmp) / "INPUT"),
            )
            gen_params = parse_incar(gen_path)
            exp_params = parse_incar(str(EXPECTED_INPUT))

            # Compute the Jaccard similarity of the parameter sets
            gen_keys = set(gen_params.keys())
            exp_keys = set(exp_params.keys())

            intersection = gen_keys & exp_keys
            union = gen_keys | exp_keys
            jaccard = len(intersection) / len(union) if union else 0

            # At least 90% of the parameters match
            assert jaccard > 0.85, (
                f"INPUT parameter sets diverge: jaccard={jaccard:.2f}, "
                f"generated_only={gen_keys - exp_keys}, "
                f"expected_only={exp_keys - gen_keys}"
            )


if __name__ == "__main__":
    # When run directly, show verbose output
    pytest.main([__file__, "-v", "--tb=short", "-s"])
