"""
aiida_orbgen.calculations.pseudo_family - Pseudo-family utilities for SIAB workflow

Centralizes every operation that turns the UPF + ORB files generated by SIAB
into an AiiDA ``AtomicOrbitalFamily``:

- :func:`resolve_paths_from_json`  : resolve the UPF/ORB/family_label paths from
  the SIAB JSON + generate_all result
- :func:`resolve_family_label`     : infer the family label from the ORB/UPF file names
- :func:`family_exists`            : check whether the family already exists
- :func:`build_orb_family`         : create / fetch the family
- :func:`ensure_pseudo_family`     : check or create it (used by WorkChains)

Dependencies
------------
- ``aiida_orbgen.static.defaults``    : DEFAULT_FAMILY_LABEL_TEMPLATE
- ``aiida_orbgen.interfaces``         : generate_all_from_json
- ``aiida-abacus``                    : AtomicOrbitalData / Family / Collection
"""
from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Optional

# The AiiDA profile must be loaded first (almost all functions here use orm.QueryBuilder)
from aiida import load_profile
load_profile()

from aiida import orm
from aiida_abacus.group.orb_group import AtomicOrbitalFamily

from aiida_orbgen.static.defaults import DEFAULT_FAMILY_LABEL_TEMPLATE


__all__ = [
    "resolve_paths_from_json",
    "resolve_family_label",
    "family_exists",
    "family_content_pairs",
    "file_md5",
    "label_for_pair",
    "build_orb_family",
    "ensure_pseudo_family",
]


# ===========================================================================
#  Path / family label resolution
# ===========================================================================


def resolve_upf_path(pseudo_dir: str, *bases: "os.PathLike | str") -> str:
    """Resolve ``config["pseudo_dir"]`` against the given base directories.

    SIAB itself interprets a relative ``pseudo_dir`` relative to the JSON file
    it was handed.  In the AiiDA path that JSON is a *copy* written into the run
    directory (``workflows.batch.run_siab_pipeline``), never the file the user
    wrote — so the base has to be chosen explicitly instead of being assumed.

    Absolute paths are returned as-is.  A relative path is tried against each
    base in order, and the first existing candidate wins; if none exists the
    error lists every location that was tried, because the previous behaviour
    (silently returning a path inside a ``/tmp`` tempfile) surfaced much later
    as "pseudo family not registered".
    """
    if not pseudo_dir:
        raise ValueError(
            "the SIAB config has no 'pseudo_dir'; set static.pseudo_path in "
            "input.json or pseudo_dir in the orbgen preset"
        )
    candidate = Path(pseudo_dir).expanduser()
    if candidate.is_absolute():
        return str(candidate)

    tried = []
    for base in bases:
        if not base:
            continue
        resolved = (Path(base).expanduser() / candidate).resolve()
        if resolved.is_file():
            return str(resolved)
        tried.append(str(resolved))
    raise FileNotFoundError(
        f"pseudo_dir={pseudo_dir!r} is relative and was not found under "
        f"{tried or ['<no base directory given>']}. Use an absolute path "
        f"(input.json['static']['pseudo_path'] is the canonical way)."
    )


def resolve_paths_from_json(siab_json_path: str, siab_result: dict) -> dict:
    """Infer the UPF/ORB paths and the family label from the SIAB JSON and the
    value returned by ``generate_all_from_json``.

    Returns
    -------
    dict
        ``{"upf_path", "orb_path", "family_label"}``
    """
    siab_json_path = os.path.abspath(siab_json_path)
    with open(siab_json_path, "r", encoding="utf-8") as f:
        config = json.load(f)

    # The JSON is the config copy in the run directory; the UPF may also sit
    # next to it or in the current working directory (SIAB's own convention for
    # the shipped examples is a relative "./X.upf").
    upf_path = resolve_upf_path(
        config.get("pseudo_dir", ""),
        Path(siab_json_path).parent,
        Path.cwd(),
    )

    orb_path = siab_result["nsw"]

    family_label = resolve_family_label(
        orb_filename=siab_result["nsw_filename"],
        upf_path=upf_path,
    )
    return {
        "upf_path": upf_path,
        "orb_path": orb_path,
        "family_label": family_label,
    }


def _extract_zval_from_upf(upf_path: str) -> str:
    """Extract z_valence (the number of valence electrons) from the UPF PP_HEADER."""
    try:
        with open(upf_path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read(8192)
        match = re.search(r'z_valence="\s*([\d.]+)', content)
        if match:
            zval_float = float(match.group(1))
            return str(int(round(zval_float)))
        match = re.search(r"z_valence\s*=\s*([\d.]+)", content)
        if match:
            zval_float = float(match.group(1))
            return str(int(round(zval_float)))
    except Exception:
        pass
    return "?"


def resolve_family_label(*, orb_filename: str, upf_path: str) -> str:
    """Infer the family label from the ORB / UPF file names.

    Family label format (example):
        siab-u-nr-pbe-z6-nsw-9au-100Ry-g
        |     | |   |  |    |    |     |
        |     | |   |  |    |    |     +-- lmax  (highest ORB angular momentum s/p/d/f/g/...)
        |     | |   |  |    |    +-- ecut (Ry)
        |     | |   |  |    +-- rcut (au)
        |     | |   |  +-- zval  (number of valence electrons, read from the UPF PP_HEADER)
        |     | |   +-- literal "nsw"
        |     +-- pp_xc  (UPF XC: pbe/pz/pbesol, with the -n-nc suffix stripped)
        |     +-- rel  (fr=fully-relativistic, nr=non-relativistic)
        +-- element (lower case)
    """
    # ---- ORB file name: {element}_{xc}_{rcut}au_{ecut}Ry_{nzeta}.orb ----
    stem = Path(orb_filename).stem
    parts = stem.split("_")
    element = parts[0] if len(parts) >= 1 else ""
    rcut_str = parts[2] if len(parts) >= 3 else ""
    ecut_str = parts[3] if len(parts) >= 4 else ""
    nzeta_str = parts[4] if len(parts) >= 5 else ""

    rcut = rcut_str.rstrip("au") if rcut_str else "?"
    ecut = ecut_str.rstrip("Ry") if ecut_str else "?"
    lmax = nzeta_str[-1] if nzeta_str else "?"

    # ---- UPF file name: {elem}.{pp_part}.upf ----
    upf_name = Path(upf_path).name
    upf_stem = upf_name.rsplit(".", 1)[0]  # drop .upf
    upf_parts = upf_stem.split(".")
    pp_part = upf_parts[1] if len(upf_parts) >= 2 else ""
    if pp_part.startswith("rel-"):
        rel = "fr"
        pp_xc_raw = pp_part[len("rel-"):]
    else:
        rel = "nr"
        pp_xc_raw = pp_part
    # strip the -n / -nc / -n-nc ... suffixes
    pp_xc = re.sub(r"(-\w+)*$", "", pp_xc_raw)

    zval = _extract_zval_from_upf(upf_path)

    if not element:
        return f"siab-{stem.lower()}"

    return DEFAULT_FAMILY_LABEL_TEMPLATE.format(
        element=element.lower(),
        rel=rel,
        pp_xc=pp_xc,
        zval=zval,
        rcut=rcut,
        ecut=ecut,
        lmax=lmax,
    )


# ===========================================================================
#  Pseudo-family check / build
# ===========================================================================


def family_exists(family_label: str) -> Optional[int]:
    """Return the pk of the family; return ``None`` when it does not exist."""
    qb = orm.QueryBuilder()
    qb.append(AtomicOrbitalFamily, filters={"label": family_label})
    row = qb.first()
    if row is None:
        return None
    return row[0].pk


def file_md5(path: "os.PathLike | str") -> str:
    """md5 of a file's bytes — the digest ``UpfData``/``AtomicOrbitalData`` store.

    Computed here from the files on disk (never by opening a stored node), so the
    content check below costs nothing and works on a read-only object store.
    """
    digest = hashlib.md5()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def family_content_pairs(family_label: str) -> set[tuple[str, str]]:
    """``(upf md5, orbital md5)`` pairs held by the family with this label.

    Attributes only, so no repository access is needed.  An empty set means either
    "no such family" or "family without members"; the callers only care that the
    requested pair is not in it.
    """
    from aiida_abacus.data.orbital import AtomicOrbitalData

    qb = orm.QueryBuilder()
    qb.append(AtomicOrbitalFamily, filters={"label": family_label}, tag="family")
    qb.append(
        AtomicOrbitalData,
        with_group="family",
        project=["attributes.md5", "attributes.md5_orbital"],
    )
    return {(upf_md5, orb_md5) for upf_md5, orb_md5 in qb.all()}


def label_for_pair(
    base_label: str,
    upf_path: "os.PathLike | str",
    orb_path: "os.PathLike | str",
    *,
    existing=family_content_pairs,
) -> tuple[str, str]:
    """The family label to register under, plus a note when the name was taken.

    A pseudo family is a *name* for one ``(UPF, ORB)`` pair, but
    :func:`ensure_pseudo_family` used to skip creation whenever the name already
    existed — so a freshly generated pseudopotential whose file name follows the
    same convention silently inherited the family built from the *previous* one.
    Measured on the live profile (2026-09-29): ``project/u_14ve/U.pbe-n-nc.UPF``
    and ``project/pseudo/U.pbe-n-nc.14ve.UPF`` are different files (md5
    ``024f9a43…`` vs ``166049de…``) that both derive
    ``siab-u-nr-pbe-z14-nsw-10au-150Ry-g`` — the label of the family holding the
    old UPF.  The children would have run with the old pseudopotential while
    SIAB's reference DFT used the new one, and nothing would have said so.

    Returns
    -------
    (label, note)
        ``label`` is ``base_label`` when it is free or already holds exactly these
        files, otherwise ``base_label`` plus a short digest of the pair.  ``note``
        is a human-readable explanation, empty when there is nothing to explain.
    """
    upf_md5 = file_md5(upf_path)
    orb_md5 = file_md5(orb_path)
    pairs = existing(base_label)
    if not pairs or (upf_md5, orb_md5) in pairs:
        return base_label, ""

    digest = hashlib.md5(f"{upf_md5}:{orb_md5}".encode()).hexdigest()[:6]
    label = f"{base_label}-{digest}"
    other = sorted({pair[0][:8] for pair in pairs})
    note = (
        f"family '{base_label}' already exists but holds different file(s) "
        f"(stored upf md5 {other}, requested {upf_md5[:8]} = "
        f"{Path(upf_path).name}); registering '{label}' instead. A pseudo family is "
        f"a name for one (UPF, ORB) pair, and reusing the old label would run the "
        f"children with the previous pseudopotential while SIAB's reference DFT "
        f"used {Path(upf_path).name}."
    )
    return label, note


def build_orb_family(
    upf_path: str,
    orb_path: str,
    family_label: str,
    description: str = "Built by aiida-orbgen (SIAB workflow)",
    overwrite: bool = False,
) -> str:
    """Build an ``AtomicOrbitalFamily`` from UPF + ORB (3 steps: Data -> Collection -> Family)."""
    from aiida_abacus.data.orbital import AtomicOrbitalData

    if not os.path.exists(upf_path):
        raise FileNotFoundError(f"UPF does not exist: {upf_path}")
    if not os.path.exists(orb_path):
        raise FileNotFoundError(f"ORB does not exist: {orb_path}")

    # Step 1: AtomicOrbitalData (UPF+ORB pair, de-duplicated by md5)
    print(f"[1/3] AtomicOrbitalData.get_or_create({Path(upf_path).name}, {Path(orb_path).name})")
    orb_data = AtomicOrbitalData.get_or_create(upf_path, orb_path)
    if not orb_data.is_stored:
        orb_data.store()
    print(f"      -> pk={orb_data.pk}, stored={orb_data.is_stored}")

    # Step 2: AtomicOrbitalCollection
    coll_label = family_label + "-collection"
    print(f"[2/3] collection '{coll_label}'")
    coll, _ = orm.Group.collection.get_or_create(label=coll_label)
    coll.description = description
    if orb_data.pk not in [n.pk for n in coll.nodes]:
        coll.add_nodes([orb_data])
        print(f"      -> node {orb_data.pk} added (collection now holds {coll.count()})")
    else:
        print(f"      -> node {orb_data.pk} is already in the collection")

    # Step 3: AtomicOrbitalFamily
    print(f"[3/3] family '{family_label}'")
    existing_pk = family_exists(family_label)
    if existing_pk is not None:
        if overwrite:
            fam_node = orm.load_node(existing_pk)
            fam_node.delete()
        else:
            print(f"      -> family already exists (pk={existing_pk}), skipping creation")
            return family_label

    family = AtomicOrbitalFamily(label=family_label, description=description)
    family.store()
    if orb_data.pk not in [n.pk for n in family.nodes]:
        family.add_nodes([orb_data])
    print(f"      -> node {orb_data.pk} added (family now holds {family.count()})")
    print(f"==>  family label: {family_label}")
    return family_label


def ensure_pseudo_family(
    upf_path: str,
    orb_path: str,
    family_label: str,
    *,
    build_if_missing: bool = True,
    description: str = "Built by aiida-orbgen (SIAB workflow)",
) -> str:
    """Check whether the family exists; build it when missing and ``build_if_missing=True``.

    Returns
    -------
    str
        the label the caller must use.  This is ``family_label`` unless that name
        already belongs to a family built from *other* files, in which case a
        content-suffixed label is registered instead (see :func:`label_for_pair`) —
        the caller has to use the return value, not its argument.
    """
    label, note = label_for_pair(family_label, upf_path, orb_path)
    if note:
        print(f"WARNING: {note}")
    existing_pk = family_exists(label)
    if existing_pk is not None:
        print(f"family '{label}' already exists (pk={existing_pk}), skipping creation")
        return label
    if not build_if_missing:
        raise RuntimeError(
            f"family '{label}' does not exist and build_if_missing=False"
        )
    return build_orb_family(upf_path, orb_path, label, description=description)
